import os
from digitalshadow.utils.checkcal import check_calibration
from dotenv import load_dotenv
import numpy as np
from scipy.fft import rfft, irfft, rfftfreq, next_fast_len
from scipy.signal import resample_poly
import scipy.io.wavfile as wav
from math import gcd
from digitalshadow.underwater_sim.ambient_noise import get_noise_config, add_ambient_noise
from digitalshadow.utils.test_bathymetry import get_depth_gebco

FS_OUT = 96000
P_REF = 1e-6

# FFT data of the source signal (constant during the entire simulation)
FFT_X = None
FFT_f = None
FFT_nfft = None

def read_arr(filename):
    """
    Reads the .arr file generated by BELLHOP for a single source and a single receiver.
    The HYDROMATE simulation must be run with nrd = nrr = 1.

    Returns
    -------
    arrivals : list of tuples, one per arrival:
               (amplitude, phase [deg], delay_re [s], delay_im [s],
                departure angle [deg], arrival angle [deg], n_top, n_bot)
    """
    with open(filename) as f:
        lines = [l.strip() for l in f if l.strip()]   # Ignore possible empty lines

    # First two lines are skipped (Header: '2D' and frequency)
    nsd = int(lines[2].split()[0])   # NSD + SD
    nrd = int(lines[3].split()[0])   # NRD + RD
    nrr = int(lines[4].split()[0])   # NR  + RR
    if nsd != 1 or nrd != 1 or nrr != 1:
        raise ValueError(f"Expected nsd = nrd = nrr = 1, and got nsd = {nsd}, nrd = {nrd}, nrr = {nrr}.")

    narr = int(lines[6])    # Number of arrivals at the receiver

    arrivals = []
    for line in lines[7:7 + narr]:
        p = line.split()
        arrivals.append((float(p[0]),   # Amplitude
                         float(p[1]),   # Phase (degrees)
                         float(p[2]),   # Time of arrival - REAL (seconds)
                         float(p[3]),   # Time of arrival - IMAGINARY (seconds)
                         float(p[4]),   # Departure angle at TX (degrees)
                         float(p[5]),   # Arrival angle at RX (degrees)
                         int(p[6]),     # Number of reflections on water surface
                         int(p[7])))    # Number of reflections on seafloor

    return arrivals

def synth_rx(src_path, sim_name, arrivals, fs, n_out, t0):
    global FFT_X, FFT_f, FFT_nfft

    arr = np.asarray(arrivals, dtype=np.float64).reshape(-1, 8)

    # Amplitude, phase and time of travel
    amp, ph, tau = arr[:, 0], arr[:, 1], arr[:, 2]
    d = tau - t0

    # keep only arrivals that contributes to the OUT file
    keep = (d >= 0) & (d < n_out // fs)
    amp, ph, d = amp[keep], ph[keep], d[keep]

    # ========= Source signal =========
    if FFT_X is None or FFT_f is None:
        # Load the audio file
        src = load_audio_source(src_path,FS_OUT,sl_db=150)

        # Compute the minimum length required to achieve the target output length
        x = np.zeros(n_out)
        x[:min(n_out, len(src))] = src[:n_out]
        nfft = next_fast_len(2 * n_out) 

        # Compute the FFT
        FFT_X = rfft(x, n=nfft)
        FFT_f = rfftfreq(nfft, 1 / fs)
        FFT_nfft = nfft

    # ========= Impulse response =========
    c = amp * np.exp(1j * np.deg2rad(ph))
    H = c @ np.exp(-2j * np.pi * np.outer(d, FFT_f))

    # Multiplication in frequency domain and transformation in time domain
    return irfft(FFT_X * H, n=FFT_nfft)[:n_out]

def load_audio_source(filepath, fs_target, sl_db=None, active_thresh_db=-40.0):
    """
    Loads the source track. If sl_db is given, the track is scaled to physical
    pressure [Pa] at 1 m, such that its active RMS equals SL (dB re 1 µPa @ 1 m).
    """
    fs_orig, data = wav.read(filepath)
    data = data.astype(np.float64)

    # Resample if source and target sampling frequency do not match
    if fs_orig != fs_target:
        g = gcd(fs_target, fs_orig)
        data = resample_poly(data, fs_target // g, fs_orig // g)
        print(f"Resampled from {fs_orig} Hz to {fs_target} Hz")

    # Nomalization with respect to the maximum
    data /= np.max(np.abs(data))

    # Calibration
    if False:
        p_rms_target = P_REF * 10 ** (sl_db / 20) 
        data *= p_rms_target / np.sqrt(np.mean(data**2))
        print(f"Source calibrated: SL = {sl_db:.1f} dB re 1 µPa @ 1 m")

    return data

def from_arr_to_wav(TX_POS, number_mic: int,sim_name=str, n_arrivals=0, sl_db=150, sim_timestamp=0, floater_number=0,
                    add_noise=False, noise_seed=1, save_clean=False):
    """
    Generates the received pressure [Pa] for N hydrophones from Bellhop .arr files.

    Parameters
    ----------
    arr_input_folder : folder containing the .arr files (H1.arr, H2.arr, ...)
    number_mic   : number of .arr files to read
    n_arrivals   : number of earliest arrivals to keep per hydrophone (0 = all)
    sl_db        : source level, dB re 1 µPa @ 1 m (None = old arbitrary scale)
    add_noise    : True/False forces ambient noise on/off; None = use the global
                   ADD_AMBIENT_NOISE flag (environment variable)
    noise_seed   : noise seed; None = use NOISE_SEED (if defined) or random
    save_clean   : if True, also save the noise-free traces (H{i}_clean.npy)
    """

    # Arrivals for each hydrophone (sorted by time of arrival)
    arrivals_per_mic = []
    for i in range(1, number_mic + 1):
        arrivals = read_arr(os.path.join(f"HM_out_{sim_name}_{i}", f"HM_out_{sim_name}.arr"))

        # Sort by arrivals by REAL delay ascending order
        used = sorted(arrivals, key=lambda a: a[2])   
        if n_arrivals > 0:
            used = used[:n_arrivals] # Keep only the earliest arrivals
            
        if not used:
            print(f"[WARNING] T{sim_timestamp}: Floater {floater_number}, hydrophone {i}: no arrivals found.")
        
        arrivals_per_mic.append(used)

    # Common time reference: earliest arrival over all hydrophones
    t0 = None
    for used in arrivals_per_mic:
        # Skip hydrophones without arrivals
        if not used:
            continue

        first_delay = used[0][2]    # Take the ToA (3rd value) of the first arrival.
        if t0 is None or first_delay < t0:
            t0 = first_delay

    if t0 is None:
        t0 = 0.0

    # == Synthesis + calibration check (in Pa)
    clean = []
    for i, used in enumerate(arrivals_per_mic, start=1):
        if used:
            load_dotenv()
            src_path = os.getenv('SRC_AUDIO_PATH')
            rx = synth_rx(src_path, sim_name, used, FS_OUT, FS_OUT, t0)
        else:
            rx = np.zeros(FS_OUT)

        #src = load_audio_source(src_path, FS_OUT, sl_db=sl_db)
        #check_calibration(rx, src, used, FS_OUT, sl_db, label=f"H{i}")

        clean.append(rx)

    # == Ambient noise (Wenz), optional
    cfg = get_noise_config()

    if add_noise:
        rng = np.random.default_rng(noise_seed)
        print(f"Ambient noise ON: shipping={cfg['shipping']}, wind={cfg['wind']} m/s, "
              f"extra={cfg['extra_db']:+.1f} dB, band {cfg['f_low']:.0f}-{cfg['f_high']:.0f} Hz, "
              f"seed={noise_seed}")
        out, _ = add_ambient_noise(clean, FS_OUT,
                                   shipping=cfg["shipping"], wind=cfg["wind"],
                                   extra_db=cfg["extra_db"], rng=rng,
                                   f_low=cfg["f_low"], f_high=cfg["f_high"])
    else:
        #print("Ambient noise OFF")
        out = clean

    # == Save
    for i, rx in enumerate(out, start=1):
        L_MAX = 500
        depth = get_depth_gebco(TX_POS[0],TX_POS[1])
        
        if(L_MAX <= depth):
            RX_EST_BEST = sl_db - 20*np.log10(L_MAX)
        else:
            RX_EST_BEST = sl_db - (20*np.log10(depth) + 10*np.log10(L_MAX/depth))

        #print(f"RX BEST: {RX_EST_BEST}")
        #print(f"RX TRUE: {20 * np.log10(np.sqrt(np.mean(rx**2)) / P_REF)}")
        
        level_db = RX_EST_BEST - (-9)
        rng = np.random.default_rng(i+(noise_seed**2))
        sigma = 1e-6 * 10 ** (level_db / 20)          # Pa RMS
        #rx =  rx + 0 + sigma * rng.standard_normal(len(rx))
        #print(f"RX LEVEL+NOISE: {20 * np.log10(np.sqrt(np.mean(rx**2)) / P_REF)}")

        wav.write(os.path.join(sim_name, "SynthTracks", f"T{sim_timestamp}_F{floater_number}_H{i}.wav"),FS_OUT,rx)
        if save_clean and add_noise:
            wav.write(os.path.join(sim_name, "SynthTracks", f"T{sim_timestamp}_F{floater_number}_H{i}_clean.wav"), FS_OUT, clean[i - 1])